-- MySQL Script generated by MySQL Workbench
-- Tue Jul 28 10:48:53 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Table `conversations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conversations`
(
    `id`          INT          NOT NULL,
    `owner`       VARCHAR(64)  NOT NULL,
    `title`       VARCHAR(256) NULL,
    `invite_link` VARCHAR(128) NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_conversations_players_idx` (`owner` ASC),
    CONSTRAINT `fk_conversations_players`
        FOREIGN KEY (`owner`)
            REFERENCES `players` (`uuid`)
            ON DELETE CASCADE
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `players`
(
    `uuid`                  VARCHAR(64) NOT NULL,
    `vk`                    INT         NOT NULL,
    `nickname`              VARCHAR(64) NOT NULL,
    `selected_conversation` INT         NULL,
    PRIMARY KEY (`uuid`),
    UNIQUE INDEX `vk_UNIQUE` (`vk` ASC),
    INDEX `fk_players_conversations1_idx` (`selected_conversation` ASC),
    CONSTRAINT `fk_players_conversations1`
        FOREIGN KEY (`selected_conversation`)
            REFERENCES `conversations` (`id`)
            ON DELETE SET NULL
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conversation_members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conversation_members`
(
    `player`       VARCHAR(64) NOT NULL,
    `conversation` INT         NOT NULL,
    PRIMARY KEY (`player`, `conversation`),
    INDEX `fk_players_has_conversations_conversations1_idx` (`conversation` ASC),
    INDEX `fk_players_has_conversations_players1_idx` (`player` ASC),
    CONSTRAINT `fk_players_has_conversations_players1`
        FOREIGN KEY (`player`)
            REFERENCES `players` (`uuid`)
            ON DELETE CASCADE
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_players_has_conversations_conversations1`
        FOREIGN KEY (`conversation`)
            REFERENCES `conversations` (`id`)
            ON DELETE CASCADE
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;