# =====================RU=====================
# VK токены группы
# Если вы получаете ошибку слишком много запросов в секунду, просто сгенерируйте токены и добавьте их сюда
# Пожалуйста не пишите токены от разных групп, а то плагину *****
# =====================EN=====================
# VK GROUP TOKENS
# If you get exception too many requests per second, add another tokens here, if you dont get use one token
# Please DO NOT write tokens from different groups
token:
  - "Place group token here|Сюда писать токен группы"
# =====================RU=====================
# Префикс с которого начинаются команды
# =====================EN=====================
# Commands starts with:
command_prefix: "/"
# Id or domains
# =====================RU=====================
# Список админов
# Они могут писать команды на сервер
# Вкшные ID или домены (то чо после vk.com/ идёт на странице юзера(id писать без id))
# =====================EN=====================
# Admin list
# They can execute commands on server
admins:
  - spliterash
# =====================RU=====================
# Если включено, будут приходить сообщения о входе или выходе игрока с сервера
# =====================EN=====================
# If enable, you receive message about enter/exit players
join_message: true
# =====================RU=====================
# Если включено, будет писать о том что игрок умер (на банже работать не будет)
# =====================EN=====================
# If enable, you receive messsage about player die
die_message: true



mysql_enable: false
mysql_host: localhost
mysql_port: 3306
mysql_db: vk
mysql_user: root
mysql_password: 1234