# VK GROUP TOKEN
token: ""
# LongPoll wait time, DO NOT SET 0
wait: 5000
# Conservation mode (If disable, Only commands and personal messages)
conversation_mode: true
# Conservation invite link
invite_link: 'https://vk.me/join/AJQ1dzBN8hfFA48mn7pGj6b7'